name: Security Audit
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/*.go"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install Gosec
        run: go get github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Security Audit
        run: gosec ./...
